#!/usr/bin/env bash

entries=(
    "  Logout"
    "󰒲  Suspend"
    "  Reboot"
    "  Hibernate"
    "  Reboot into BIOS"
)

case "$1" in
    "") printf '%s\n' "${entries[@]}" ;;
    "  Logout") hyprctl dispatch exit ;;
    "󰒲  Suspend") systemctl suspend ;;
    "  Hibernate") systemctl hibernate ;;
    "  Reboot") systemctl reboot ;;
    "  Boot into BIOS") systemctl reboot --firware-setup ;;
esac
