general {
    after_sleep_cmd = hyprctl dispatch dpms on
}

# After 5 minutes, turn off the screen
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# After 15 minutes, hibernate the PC
listener {
    timeout = 900
    on-timeout = systemctl hibernate
}
