
 #~#~#~#~#
 # RULES #
 #~#~#~#~#

windowrule = suppressevent maximize, class:.* # Ignore maximize requests from apps

# Apparently this fixes some dragging issues with XWayland
windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

# Smart gaps (disable outer gaps if there is only one window in workspace)
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1],   gapsout:0, gapsin:0

windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
windowrule = rounding   0, floating:0, onworkspace:w[tv1]
windowrule = bordersize 0, floating:0, onworkspace:f[1]
windowrule = rounding   0, floating:0, onworkspace:f[1]

# Floating by default for some apps
windowrule = float,         class:blueman-manager
windowrule = size 1080 720, class:blueman-manager

windowrule   = float,            class:steam
windowrulev2 = tile,             class:steam, title:Steam
windowrulev2 = tile, fullscreen, class:dota2
