
 #~#~#~#~#
 # RULES #
 #~#~#~#~#

# Ignore maximize requests from apps
windowrule = match:class .*, suppress_event maximize

# Apparently this fixes some dragging issues with XWayland
windowrule = match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0, no_initial_focus on

# Smart gaps (disable outer/inset gaps for specific workspaces)
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1],   gapsout:0, gapsin:0

# Remove border and rounding on windows in those workspaces (only for non-floating windows)
windowrule {
    name = smart-borders-tv
    match:workspace = w[tv1]
    match:float = 0

    border_size = 0
    rounding = 0
}
windowrule {
    name = smart-borders-full
    match:workspace = f[1]
    match:float = 0

    border_size = 0
    rounding = 0
}

# Floating by default for blueman-manager
windowrule {
    name = blueman
    match:class = blueman-manager

    float = 1
    size = 1080 720
}

# Steam
windowrule = match:class steam, float 1

windowrule = match:title Steam, tile 1
windowrule = match:class dota2, tile 1, fullscreen 1
